### ISSUE TITLE
BUG: `POST /topics/:topicId/votes/:voteId/sign` - No digidoc in session - 500 Internal Server Error

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#107]
**Overview**

Not too often, 1but sometimes `POST /topics/:topicId/votes/:voteId/sign`  fails with following error:

```
1 Feb 2017 18:31:03.708  345 <158>1 2017-02-01T16:31:02.718770+00:00 host heroku router - at=info method=POST path="/api/topics/dbe5cd08-afe1-47fd-aac6-6abb8e1f24ea/votes/aab3b420-e26d-45f4-8dcf-a91b30ae6572/sign" host=citizenos.com request_id=f4805703-14ba-4550-a8d0-ded209f00522 fwd="x" dyno=web.1 connect=0ms service=356ms status=500 bytes=339
» 1 Feb 2017 18:31:03.748  182 <190>1 2017-02-01T16:31:02.711638+00:00 host app web.1 - [32m[2017-02-01 16:31:02.711] [INFO] production - [39mDB QUERY. Executed (310262e6-bb8f-49cc-80eb-5ba4b0c16656): ROLLBACK;
» 1 Feb 2017 18:31:03.825  253 <190>1 2017-02-01T16:31:02.714732+00:00 host app web.1 - [32m[2017-02-01 16:31:02.714] [INFO] production - [39mSequelize error handler middleware activated. { [Error: No digidoc in session] name: 'Error', message: 'No digidoc in session', code: 101 }
» 1 Feb 2017 18:31:03.825  63 <190>1 2017-02-01T16:31:02.714735+00:00 host app web.1 - Error
» 1 Feb 2017 18:31:03.825  114 <190>1 2017-02-01T16:31:02.714736+00:00 host app web.1 -     at Object.<anonymous> (/app/libs/ddsClient.js:51:44)
» 1 Feb 2017 18:31:03.825  99 <190>1 2017-02-01T16:31:02.714737+00:00 host app web.1 -     at Module._compile (module.js:409:26)
» 1 Feb 2017 18:31:03.825  113 <190>1 2017-02-01T16:31:02.714737+00:00 host app web.1 -     at Object.Module._extensions..js (module.js:416:10)
» 1 Feb 2017 18:31:03.825  95 <190>1 2017-02-01T16:31:02.714738+00:00 host app web.1 -     at Module.load (module.js:343:32)
» 1 Feb 2017 18:31:03.825  105 <190>1 2017-02-01T16:31:02.714739+00:00 host app web.1 -     at Function.Module._load (module.js:300:12)
» 1 Feb 2017 18:31:03.825  98 <190>1 2017-02-01T16:31:02.714739+00:00 host app web.1 -     at Module.require (module.js:353:17)
» 1 Feb 2017 18:31:03.825  99 <190>1 2017-02-01T16:31:02.714740+00:00 host app web.1 -     at require (internal/module.js:12:17)
» 1 Feb 2017 18:31:03.825  104 <190>1 2017-02-01T16:31:02.714740+00:00 host app web.1 -     at Object.<anonymous> (/app/app.js:145:22)
» 1 Feb 2017 18:31:03.825  99 <190>1 2017-02-01T16:31:02.714741+00:00 host app web.1 -     at Module._compile (module.js:409:26)
» 1 Feb 2017 18:31:03.825  113 <190>1 2017-02-01T16:31:02.714741+00:00 host app web.1 -     at Object.Module._extensions..js (module.js:416:10)
```

** How often does it happen? **

* February 2017 - 6 times while there were thousands of signings
* October 2018 - 1

My gut feeling says the problem is on DigiDocService side, but not proven guilty.

**TODO**

- [ ] Review the related code, see if there is any chance that Citizen OS API does not create the doc in session
- [ ] IF code seems to be ok, ask DigiDocService (DDS) helpdesk, if it's a know issue.

**Comment by ilmartyrk** [comment]
Closing as we are not using DDS anymore
