### ISSUE TITLE
BUG: Etherpad error while multiple users view a document

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#204]
Error:
```
2019-03-05T10:14:42.965494+00:00 app[web.1]: [33m[2019-03-05 10:14:42.965] [WARN] console - [39mError: Won't apply USER_CHANGES, because it contains an already accepted changeset
2019-03-05T10:14:42.965498+00:00 app[web.1]:     at Object.callback (/app/etherpad-lite/src/node/handler/PadMessageHandler.js:753:33)
2019-03-05T10:14:42.965500+00:00 app[web.1]:     at /app/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:149:17
2019-03-05T10:14:42.965501+00:00 app[web.1]:     at /app/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:378:7
2019-03-05T10:14:42.965503+00:00 app[web.1]:     at exports.database.get (/app/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:144:5)
2019-03-05T10:14:42.965504+00:00 app[web.1]:     at exports.database.getSub (/app/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:350:8)
2019-03-05T10:14:42.965507+00:00 app[web.1]:     at doOperation [as operatorFunction] (/app/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:143:18)
2019-03-05T10:14:42.965508+00:00 app[web.1]:     at exports.channels.emit (/app/etherpad-lite/src/node_modules/channels/channels.js:49:11)
2019-03-05T10:14:42.965510+00:00 app[web.1]:     at exports.database.getSub (/app/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:82:17)
2019-03-05T10:14:42.965512+00:00 app[web.1]:     at Pad.getRevisionChangeset (/app/etherpad-lite/src/node/db/Pad.js:139:6)
2019-03-05T10:14:42.965513+00:00 app[web.1]:     at /app/etherpad-lite/src/node/handler/PadMessageHandler.js:737:15
2019-03-05T10:14:42.965515+00:00 app[web.1]:     at Object.async.whilst (/app/etherpad-lite/src/node_modules/async/lib/async.js:678:13)
2019-03-05T10:14:42.965516+00:00 app[web.1]:     at /app/etherpad-lite/src/node/handler/PadMessageHandler.js:731:13
2019-03-05T10:14:42.965518+00:00 app[web.1]:     at /app/etherpad-lite/src/node_modules/async/lib/async.js:610:21
2019-03-05T10:14:42.965519+00:00 app[web.1]:     at /app/etherpad-lite/src/node_modules/async/lib/async.js:249:17
2019-03-05T10:14:42.965520+00:00 app[web.1]:     at iterate (/app/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
2019-03-05T10:14:42.965522+00:00 app[web.1]:     at /app/etherpad-lite/src/node_modules/async/lib/async.js:160:25
2019-03-05T10:14:42.980891+00:00 app[web.1]: [32m[2019-03-05 10:14:42.980] [INFO] ueberDB - [39mFlushed 1 values
2019-03-05T10:14:43.047781+00:00 app[web.1]: [32m[2019-03-05 10:14:43.047] [INFO] access - [39m[LEAVE] Pad "ac8b66a4-ca56-4d02-8406-5e19da73d7ce": Author "a.0tS3hi164Bze68Xk" on client JzN-Vaz3td1_cnHOAABi with IP "xx.xxx.x.xx, xx.xx.xxxx.x" left the pad
```

**Comment by ilmartyrk** [comment]
![screenshot_20190305-123015_chrome](https://user-images.githubusercontent.com/19904307/53799618-6ddbf080-3f43-11e9-8f6b-315ee8aa764a.jpg)

**Comment by tiblu** [comment]
Interesting that while no changes are made to a document, EP spams client with new changesets - 
![image](https://user-images.githubusercontent.com/7405383/53800746-13905f00-3f46-11e9-97c7-8776fb23831f.png)

**Comment by tiblu** [comment]
User disconnect on "badChangeset"
![image](https://user-images.githubusercontent.com/7405383/53800862-65d18000-3f46-11e9-9be2-65d2ab8f8f5b.png)

**Comment by ilmartyrk** [comment]
Was caused by a buggy plugin ep_title_limit, that started spamming with revisions when more than one user was on the pad.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
